Iter13
komogortzef/metrics pull request #22
Opened 2024-06-23 07:35 UTC by komogortzef

2024-06-24 23:30 UTC, avhitrov requested changes
Решение хорошее, есть несколько замечаний - в комментариях к коду.

2024-06-24 23:30 UTC, avhitrov commented on internal/server/dbStore.go
> +	}
При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после цикла необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку:
```
if err:= rows.Err(); err != nil {
    return nil, err
}
```

2024-06-24 23:30 UTC, avhitrov commented on internal/server/memStore.go
> +func (ms *MemStorage) PutBatch(cx ctx.Context, mets []*s.Metrics) error {
Для прода такое решение подходит плохо, так как Lock()-Unlock() - довольно тяжелые операции, и выполнять их в цикле сильно дороже, чем один раз выставить Lock, сделать все действия и после снять блокировку. В данном случае лучше не думать о переиспользовании кода, а сделать единую блокировку на функцию и внутри повторить кусок из `Put`.

2024-06-24 23:30 UTC, avhitrov commented on internal/server/server.go
> +		_ = mm.Shutdown(cx)
Сначала гасится сервис на порту, а только потом отключается сторадж, Иначе при большом потоке запросов не миновать паники. В идеале еще дождаться сигнала от горутины, синхронизирующей файловый дамп, если таковая запушена.

2024-06-25 09:07 UTC, komogortzef commented on internal/server/memStore.go
> +func (ms *MemStorage) PutBatch(cx ctx.Context, mets []*s.Metrics) error {
Да, хотел это исправить, но благополучно забыл...

2024-06-25 09:09 UTC, komogortzef commented on internal/server/server.go
> +		_ = mm.Shutdown(cx)
Ни разу не писал логику завершения программы. Все время просто Ctrl-D )))

2024-06-28 22:55 UTC, avhitrov approved these changes
Все ок!

2024-06-29 07:30 UTC, merged